on : [workflow_dispatch]

jobs: 
 custom-js-action-job:
 
  runs-on : ubuntu-latest
  
  name : Custom JS gitHub Action
  
  steps:
    - name : First GitHub Custom Action 
      id : myjsaction
      uses: adilshehzad786/Blog-GitHub-Custom-Action@v2

      with:
       name-of-you : 'Adil'
    
    - name : Output of the TimeStamp
      run : echo "The time was ${{steps.myjsaction.outputs.time}}"
