on: [workflow_dispatch]
jobs:
 custom_js_action_job:
   runs_on: ubuntu-latest
   name: Custom JS Action
   
   steps:
    id: customaction
    uses: adilshehzad786/Blog-GitHub-Custom-Action@v2
    
    with:
     name-of-user: 'Adil Shehzad'
    -name: Get Time Output
     run: echo "The time was ${{steps.customaction.outputs.time}}"
    
 
  
